### PR TITLE
Set recent pop up button key equivalent to down arrow key

### PR DESCRIPTION
**Pull request by anton-simakov**
Resolves issue #177.

I AGREE TO THE GITUP CONTRIBUTOR LICENSE AGREEMENT

### CODE REVIEW

**Comment by swisspol** [comment]
Are you sure this works?  The diff in the XIB doesn't show a keyboard shortcut.

**Comment by anton-simakov** [comment]
Yes, now press on down arrow key opens "Recently Opened..." menu.

**Comment by swisspol** [comment]
Oh I see, it was a rendering bug of the diff by GitHub.

**Comment by swisspol** [comment]
It's merged in, thanks!

**Pull request merged**
