### PR TITLE
WIP vibrancy improvements

### PR DESCRIPTION
**Pull request by saagarjha**
This is a work-in-progress pull request so that you could take a look at how I've improved vibrancy support in GitUp. Please don't merge this as-is or close it, because I'm not done yet.

I AGREE TO THE GITUP CONTRIBUTOR LICENSE AGREEMENT

### CODE REVIEW

**Comment by saagarjha** [comment]
This pull request is not complete, since there are a lot of views that I haven't modified (mostly because I haven't used GitUp enough to know how to encounter them). In addition, I have no idea how this works (or even builds) on Mac OS X 10.8. Would you mind helping me out here?

**Comment by saagarjha** [comment]
And of course, here are a couple screenshots:

screen shot 2018-04-12 at 00 48 05
screen shot 2018-04-12 at 00 48 12
screen shot 2018-04-12 at 00 49 35
screen shot 2018-04-12 at 00 50 01
screen shot 2018-04-12 at 00 50 25
screen shot 2018-04-12 at 00 50 32

**Comment by swisspol** [comment]
Thanks for sending this in. This is not something I can help with (not take on maintaining after it lands) however due to lack of bandwidth.

**Comment by saagarjha** [comment]
Wait, so is this not a feature you want? I've been working improving this myself for the last two months, and I'd like to push those changes and get them merged.

**Comment by swisspol** [comment]
There was no update on this PR in 2 months so I thought you had abandoned it. In any case, this is a very very large diff that I don't have bandwidth to properly review / merge / maintain, sorry.

**Comment by saagarjha** [comment]
> There was no update on this PR in 2 months so I thought you had abandoned it.

I would have appreciated you asking me before closing it…

> In any case, this is a very very large diff that I don't have bandwidth to properly review / merge / maintain, sorry.

I've split the pull request into around a dozen commits for each view that I updated. There's nothing else I can do to make this smaller, because it must be done all at once; otherwise some of the views will end up being clipped by the titlebar. There's only like a hundred lines of code added in all. Is this good enough for you to look at now? I really can't do much more; I've spent a *lot* of time making this as clean as it is currently and I don't think it's possible to make GitUp look nice on Yosemite with any fewer changes.

Regarding compatibility, I still need to get my hands on a 10.8 disk image so I can test this out there; but this works well on 10.10+. Can we compromise by merging this into a test branch or something like that until then?

**Pull request closed without merging**
