### PR TITLE
Added unversioned TeamID infrastructure.

### PR DESCRIPTION
**Pull request by JanX2**
This PR makes it possible for multiple developers to build GitUp out of the box. All everyone has to do once is to create a file called "DEVELOPMENT_TEAM.xcconfig" in the "Xcode-Configurations" directory within the project directory with the following build setting:
DEVELOPMENT_TEAM = [personal TeamID]

This used to be hard-coded as "88W3E55T4B" in "Xcode-Configurations/Base.xcconfig".

"DEVELOPMENT_TEAM.xcconfig" is excluded from versioning.

Please give it a go.

### CODE REVIEW

**Comment by lucasderraugh** [comment]
@JanX2 How could we set this up to pass CI? We can't really break that 😅

**Comment by JanX2** [comment]
That’s an excellent question. It might work to include the DEVELOPMENT_TEAM.xcconfig towards the end of the Base.xcconfig and keep the hard-coded "88W3E55T4B".

**Comment by JanX2** [comment]
The above doesn’t work. DEVELOPMENT_TEAM.xcconfig needs to exist.

**Comment by JanX2** [comment]
As this is now passing CI, is there anything else preventing this from being merged?

**Comment by lucasderraugh** [comment]
Probably not, it would be nice to have info in the ReadMe. I just don’t have time to test it out fully during the week but I’ll merge it this weekend assuming it all works well on my end.

**Comment by JanX2** [comment]
Improving the ReadMe is a wonderful idea!

**Comment by JanX2** [comment]
Note: That last failure seems dubious. 

> 2417	The following build commands failed:
> 2418	GenerateDSYMFile /Users/travis/Library/Developer/Xcode/DerivedData/iGit-gxbjunwufooooacdoxgjdgsvuena/Build/Products/Release-iphonesimulator/GitUpKit.framework.dSYM /Users/travis/Library/Developer/Xcode/DerivedData/iGit-gxbjunwufooooacdoxgjdgsvuena/Build/Products/Release-iphonesimulator/GitUpKit.framework/GitUpKit
> 2419(1 failure)
> 2420The command "./travis-build.sh" exited with 65.

How can this have anything to do with a README change?

**Comment by JanX2** [comment]
Before I forget:
I AGREE TO THE GITUP CONTRIBUTOR LICENSE AGREEMENT

**Comment by lucasderraugh** [comment]
I ran the travis build again and it seemed to work fine.

**Comment by JanX2** [comment]
Odd. Hope that this issue doesn’t resurface. 

Anything else preventing a merge?

**Comment by lucasderraugh** [comment]
Just me testing out the change locally :).

**Comment by lucasderraugh** [comment]
Works like a charm. Thank you!

**Comment by lolgear** [comment]
@lucasderraugh @JanX2 
Could we add script that populate Xcode-Configurations directory with this xcconfig file?

```xcconfig
// This is personal team xcconfig.
// We use it to ease your development!
// Please, fill it with appropriate Development Team ID.

DEVELOPMENT_TEAM = FILL_PERSONAL_TEAM_HERE;
```

Thanks!

**Pull request merged**
