### PR TITLE
Fix grammar in preference text

### PR DESCRIPTION
**Pull request by gouch**

### CODE REVIEW

**Comment by swisspol** [comment]
Thanks!

**Comment by swisspol** [comment]
Hi there! Can you say you agree to the contributor's license agreement - see https://github.com/git-up/GitUp/blob/master/CONTRIBUTING.md? I forgot to ask at the time.

**Comment by gouch** [comment]
No, sorry. I see no upside to agreeing to a random document about intellectual property rights and legal claims for something this tiny. Maybe it's innocuous boilerplate, but maybe it's not.

I'm fine if you copy the grammar fix into the project without crediting me 🙂

**Comment by swisspol** [comment]
I understand. I'll roll back your PR then. It's my fault anyway, there's a handful of PRs where I wasn't paying attention and forgot to ask for CLA before merging 😞

**Pull request merged**
