### PR TITLE
Added service to open a repository in GitUp from the Finder

### PR DESCRIPTION
**Pull request by rex1fernando**
I AGREE TO THE GITUP CONTRIBUTOR LICENSE AGREEMENT

Addresses #287.

screenshot 2017-05-19 17 07 06

### CODE REVIEW

**Comment by swisspol** [comment]
This looks good thanks for sending it in. However please format the source code according to the GitUp style conventions: simply run `./format-source.sh` at the top of the repo.

**Comment by salutis** [comment]
@swisspol 

> [...] please format the source code according to the GitUp style conventions [...]

Would be nice to `cp` + `format-source.sh` + `diff` on CI. It would save you time.

**Comment by swisspol** [comment]
If somebody can update this PR to have its source formatted, I can merge it.

**Comment by rex1fernando** [comment]
Woah, sorry, I completely forgot about this. I updated it just now.

**Pull request closed without merging**
