### PR TITLE
Added simple git-flow support

### PR DESCRIPTION
**Pull request by AlexIzh**
Added git-flow: 
Item into "repository" menu.
image
image2
Creation git-flow for current repository (currently, repository should have at least one commit for it):
image3
Item into contextual menu for commit(if commit from feature/release/hotfix/improvement branch):
image4
Feature creation (the same for hotfix/release): 
image5

Finishing release/hotfix: 
image6

### CODE REVIEW

**Comment by salutis** [comment]
Suggestions:

* Change the `Git flow...` menu item to `Git Flow` (fixed capitalization, no ellipsis)
* Change the `About Git flow` menu item to `About Git Flow` (fixed capitalization)

Also, what are `improvement` branches for?

**Comment by AlexIzh** [comment]
You can read about `improvement` here: https://github.com/AlexIzh/git-flow-improvement-branch#improve

It is like `feature`. But with a little changes in semantic value. You can don't use it (I added this, because I often use it in my projects) :)

**Comment by salutis** [comment]
I see. So, the `improvement` branches are something that you invented. That's nice and all  but if we're going to add Git Flow, let's add Git Flow. Nothing more, nothing less. There is a reason why Git Flow is popular in its current form.

**Comment by AlexIzh** [comment]
Yes, you are absolutely right. Official app should contain the most popular standard git flow. All unpopular custom git flow models are case for unofficial forks. I'll remove this functionality a bit later (also, I'll add prefix for tags (in progress at the moment))

**Comment by AlexIzh** [comment]
Merged latest changes from master, why CI doesn't check it?

**Comment by rm-code** [comment]
Looks great! I hope this is going to be merged into one of the future releases.

**Comment by MichaelMallett** [comment]
WOuld this support the avh binary of git flow? As that is the only one that is actually supported. Original Git Flow has been abandoned for years.

**Comment by AlexIzh** [comment]
Original Git Flow is not product or binary app for using git, it's just rules for convenient use branches. This MR doesn't require binary [git flow](https://github.com/nvie/gitflow), it uses simple git commands for working with git flow model (similar how it does gitflow applciation from [nvie](https://github.com/nvie/gitflow)).
Maybe in the future, avh functionality will be added, but currently I don't have plans about it.

**Comment by MichaelMallett** [comment]
Ah so you're essentially recreating it.

**Comment by AlexIzh** [comment]
Yes, maybe this feature will be added later (for example, if user has avh binary, then he can use additional features from GUI). 
But I guess, currently main goal is that gitUp supports at least git flow :)

**Comment by phatmann** [comment]
Any reason this PR is still not merged? I would love gitflow integration. Every other major Git GUI has it. Yes, I can use Gitflow without it, but it would be very convenient.

**Comment by swisspol** [comment]
It's a large PR and I don't have the bandwidth to review it right now unfortunately. Can this be rebased and have `format-source.sh` run btw? thx

**Comment by phatmann** [comment]
@swisspol I am a maintainer for KIF, so I deeply understand how hard it is to find time to review and merge PRs. But as a potential user, when you see a PR that is over 9 months old, you start to wonder if the project is being maintained, even if this judgement is made unfairly. Perhaps it is time to bring in other maintainers to help you out?

**Comment by swisspol** [comment]
I used GitUp personally every day, so it is definitely maintained. Trust me, if a critical bug shows up, it'll get fixed fast 😄 

There are however no reason / bandwidth for me to add new features right now if that makes sense.

**Pull request closed without merging**
