### PR TITLE
When creating branch auto-replace ":", "[", "]" with "|", and auto-replace spaces with "_"

### PR DESCRIPTION
**Pull request by Briahas**
Hi.
Sorry for possible issues in PR presenting. First time ever.

### CODE REVIEW

**Comment by lucasderraugh** [comment]
@Briahas Thanks for the contribution! I'll get to testing this weekend. Catching up on some work this week. Out of curiosity, what are you basing the git legal branch names off of? Wouldn't want to disable legal branch names by accident.

**Comment by Briahas** [comment]
@lucasderraugh Hi! Looking forward to hear you conclusions.

If I understand you question correctly, here my Feature Request written today [https://github.com/git-up/GitUp/issues/574](url). I wrote there why.
 What I forgot to write is that - GitUp rejects branch names with **spaces**, "**[**", "**]**" and "**:**". So I decided to fix it myself :)

**Comment by lucasderraugh** [comment]
Ok, you're saying it rejects them already so this would just be automating the change. Sounds good, I'll check it out in a day or 2.

**Comment by Briahas** [comment]
I'm using this build, made from XCode, for several days. Some times it's crashing.

Is there a crashlytic?

**Comment by lucasderraugh** [comment]
There should be a crash report generated or backtrace if you’re running it from Xcode.

**Comment by lucasderraugh** [comment]
@Briahas Did you figure out what the issue was or at least get a stack trace?

**Comment by lucasderraugh** [comment]
I’m going to close this out for now, but if you resolve the issue you were having with the implementation feel free to open it up again.

**Pull request closed without merging**
