### PR TITLE
Feature/prepare commit msg

### PR DESCRIPTION
**Pull request by soberman**

### CODE REVIEW

**Comment by rggjan** [comment]
@swisspol can this be merged?

**Comment by rggjan** [comment]
Feedback I got from @swisspol on this:

The PR would need to be cleaned up first to have only minimal number of commits and it needs an explanation of what this change does.

@soberman, any chance you could change the PR to accommodate the feedback?

**Comment by soberman** [comment]
Sure, will do.

**Comment by rggjan** [comment]
Awesome, thanks! Sorry I can't be of more help, but it would be great to have this feature in the "official" gitup as well. In general it would be great if the official gitup would be continued to improve...

**Comment by soberman** [comment]
Yeah, it's a shame that the work has been kinda stalled. A great git gui!

**Comment by CrazyPython** [comment]
@soberman Try opening this branch in GitUp and using the **rewrite**, **split**, and **squash** tools to clean up your commits.

**Comment by lucasderraugh** [comment]
So I've recently taken over as temporary maintainer of GitUp. If I can get an overview of visual changes here and squash changes into a single commit, I'd love to start the discussion on merging this in.

**Comment by soberman** [comment]
Sure thing, I could actually remove most of the changes since they show my own setup...

**Comment by soberman** [comment]
@lucasderraugh alright done, you can review, squash and merge.

**Comment by lucasderraugh** [comment]
Maybe I'm just not understanding the change, but it seemed originally this was to address having the template file show up in the commit field when committing in GitUp. In my testing, this doesn't appear to be the case. If I run `git commit` in the CLI, it will show the template (as explained in the blog post listed in the original issue), however, GitUp doesn't seem to show any text at any point. I assume the purpose was to show the template in the commit text field before you commit anything?

**Comment by lucasderraugh** [comment]
I'm going to close this PR for now in my goal to get to 0 outstanding. If you can respond to my above questions, feel free to reopen. Cheers!

**Pull request closed without merging**
