### PR TITLE
Add preference to disable welcome window (default NO)

### PR DESCRIPTION
**Pull request by mtrudel**
Per #102, this adds a preference to disable display of the welcome screen. It defaults to NO, so existing behaviour is preserved.

### CODE REVIEW

**Comment by AlexIzh** [comment]
@mtrudel suggestion: change title of settings to positive. For example: 
`Show welcome screen when startup` or `Start with welcome screen` or something like this. 
Reasons: 
1) Almost all settings have positive phrases in this app (I think all should be in one style)
2) Positive phrase is used more often and intuitively more understandable

**Comment by mtrudel** [comment]
@AlexIzh I don't disagree - this was just the most expedient thing to get done. Happy to change; will defer to @swisspol for guidance.

**Comment by swisspol** [comment]
Can you add a screenshot of the updated preference window?

**Comment by mtrudel** [comment]
untitled

Upon mature reflection, I think I agree with @AlexIzh - the negative case is too confusing

**Comment by swisspol** [comment]
Yes, just make it "Show welcome window". To be clear if this setting is off, then the window is never shown, right?

**Comment by mtrudel** [comment]
Pushed an amended branch with positive logic

Per @swisspol's last, this displays 'Show welcome window' in preferences and defaults to YES, which preserves existing welcome screen behaviour. Disabling that checkbox in preferences will cause the welcome screen to not be shown under any circumstances.

**Comment by swisspol** [comment]
All good then!

**Comment by salutis** [comment]
@mtrudel Thanks!

**Pull request merged**
