### PR TITLE
Change key equivalents: ⌘P for push, ⌘L for pull

### LINKED ISSUE #179: Push/pull/fetch keyboard shortcuts
I find the remote operation commands hard to memorize. I've been using GitUp for almost a year now and these are some of the few commands use regularly but can't do naturally on any app on my computer. Here are the existing shortcuts:

| Key |      Function      |
|-----|--------------------|
| ⇧⌘F | Fetch All Branches |
| ⇧⌘T | Fetch All Tags     |
| ⇧⌘P | Push               |
| ⌘P  | Pull               |

Feel free to ask me for more details, but here's briefly why I think they're hard to memorize compared to most keyboard shortcuts:

- "Shift" doesn't have a consistent meaning. Sometimes it seems to mean "remote operation", sometimes it seems to mean "opposite.
- The Push/pull shortcuts are opposite those of GitHub Desktop, which I used for more than a year before I found GitUp. In fact, I wouldn't be surprised if some people use both apps from time to time and just give up on using these shortcuts.
- These commands are not commands you run very very frequently. You run them a few times a day, which reduces the opportunity to memorize them. (A command with similar usage frequency might be Finder's Connect to Server ⌘K.) That's why the mnemonic has to be extra good.
- Sometimes I can learn commands just by trying them. I accidentally open the "Connect to Server" dialog? No worries, I can just close it. However, these commands are the few non-undoable commands in this app, so there's less room for error.

So anyway, here's my proposal for these for these four commands:

| Key |      Function      |
|-----|--------------------|
| ⇧⌘F | Fetch All Branches |
| ⇧⌘T | Fetch All Tags     |
| ⌘P  | Push               |
| ⌘L  | Pull               |

Why "L" for pull?

1. I've seen other people use this as a command line abbreviation.
2. "Pull" ends in L
3. On the keyboard, P is further from you (you're pushing something away) and L is closer to you (you're pulling it towards you)

Why do some commands have shift and some don't? Here, the meaning of "shift" can be seen as meaning "lower level" or "uncommon" operation. Or, alternatively, screw the inconsistency, I'll be okay with this too:

| Key |      Function      |
|-----|--------------------|
| ⇧⌘F | Fetch All Branches |
| ⇧⌘T | Fetch All Tags     |
| ⇧⌘P | Push               |
| ⇧⌘L | Pull               |

---

Also, while I highly prefer a change of keyboard shortcuts, here are some other suggestions that might achieve the same goal:

- To make the commands easier to access in other ways, make the push/pull buttons easier to click (larger/closer), and add fetch buttons.
- To make the shortcuts easier to learn, display a bezel/toast/banner everytime a shortcut is pressed.
- To make the shortcuts easier to learn, make the "remote operation in progress dialog" more specific.

### PR DESCRIPTION
**Pull request by szhu**
Fixes #179.

I don't have the full Xcode setup, and I've only edited the source. Can someone check that this compiles properly?

I AGREE TO THE GITUP CONTRIBUTOR LICENSE AGREEMENT

### CODE REVIEW

**Comment by szhu** [comment]
@swisspol Added CLA.

**Comment by swisspol** [comment]
Sorry can’t merge something that hasn’t actually been tested even if the diff looks trivial.

**Comment by szhu** [comment]
I understand. I was wondering if you or a contributor could verify this for me.

**Comment by szhu** [comment]
Never got the project set up on my computer. If you have the time to test it let me know!

**Comment by NikKovIos** [comment]
Too difficult to run this repo, so waiting for someone who can do it.

**Pull request closed without merging**
