### PR TITLE
Fixed off-center search field placeholders

### PR DESCRIPTION
**Pull request by antons**
Off center placeholder is particularly bothersome on macOS Sierra. Even the default title was [drawn incorrectly](https://cloud.githubusercontent.com/assets/129705/18415307/357c6a88-77f6-11e6-869f-8d365617ac68.png) on launch. `[_searchField setNeedsLayout:YES]` forces search field to re-center the placeholder, both on launch, and during indexing.

Tested on macOS Sierra GM, and macOS El Capitan 10.11.5.

I removed your previous workaround for indexing (extra whitespace). Do you recall if you’ve tried `[_searchField setNeedsLayout:YES]` on Yosemite? If I recall correctly, search field centering had more bugs there, so this new workaround might not work. But I don’t have a machine with 10.10 to test this.

I AGREE TO THE GITUP CONTRIBUTOR LICENSE AGREEMENT

### CODE REVIEW

**Comment by swisspol** [comment]
The workarounds for this AppKit bug work on 10.8-10.11, so it's best not to change that code. Instead add a code path that's only for 10.12 and later.

**Comment by antons** [comment]
@swisspol I think placeholders were not centered before 10.10. You’re right, it’s best to avoid a regression. I updated the fix to have two separate code paths. What do you think?

**Comment by antons** [comment]
Ah, of course NSAppKitVersionNumber10_11 was declared only on 10.12 SDK, and CI runs with 10.11 SDK.

**Comment by swisspol** [comment]
You'll want to use `kCFCoreFoundationVersionNumber` like in other places in the code.

Then add something like this at the top of the file:
```
#ifndef kCFCoreFoundationVersionNumber10_12
#define kCFCoreFoundationVersionNumber10_12 ?
#endif
```

For the actual value of `kCFCoreFoundationVersionNumber10_12`, you'll have to just print it `kCFCoreFoundationVersionNumber` in the debugger.

**Comment by antons** [comment]
Thanks. Done.

**Comment by swisspol** [comment]
Looks good. Did you use the format source script?

**Comment by antons** [comment]
@swisspol Homebrew now installs clang-format 4.0.0. I modified format sources and ran it. It did not produce any changes.

**Comment by swisspol** [comment]
Thanks, I'll wait until Sierra is officially out to merge this in.

**Pull request merged**
