### PR TITLE
GraphView: Merged branches nodes selection via keyboard.

### PR DESCRIPTION
**Pull request by lolgear**
- [x] #298 
Done via `Alt` key.

### CODE REVIEW

**Comment by lolgear** [comment]
@lucasderraugh Awaiting for review :)

**Comment by lucasderraugh** [comment]
Looks good. The only thing I hit that we should fix before merging this in is that if I hold the option key and hit up when I'm already at top of tree, I hit an assertion because there is nothing higher up. We should do the same check that we do when hitting the up key normally.

**Comment by lolgear** [comment]
@lucasderraugh Could you check latest commits?
I am not sure that I have added correct guard statement.
Thanks!

**Comment by lolgear** [comment]
@lucasderraugh 
By the way, you don't close related issues that are mentioned in previous PRs. Is there special reason for it?

**Comment by lucasderraugh** [comment]
@lolgear I'll check it in a bit. I sneak it some spare time to review these here and there.

No special reason, it's most likely because I forgot. If you want you can put in the commit "Closes #_" and it should automatically close the issue for me :).

**Comment by lolgear** [comment]
@lucasderraugh 
Okey :) 
Well, I am registered at Hacktoberfest, could you add label "Hacktoberfest" to issues in my previous PRs? :)

**Comment by lucasderraugh** [comment]
"To qualify for the official limited edition Hacktoberfest shirt, you must register and make four pull requests (PRs) between October 1-31 (in any time zone). PRs can be made to any public repo on GitHub, not only the ones with issues labeled Hacktoberfest."

Doesn't sound like I need to label anything other than to encourage people to find this project and that only PRs made during October would apply.

**Comment by lucasderraugh** [comment]
Looks good, I was unable to hit any issues with it. I'm not sure it handles all cases as expected, but I'm more than happy to have this until somebody feels a need to change it. It's all additive anyway. Thanks again!

**Comment by lolgear** [comment]
Closes #298

**Comment by lolgear** [comment]
@lucasderraugh post a comment "Closes # _" in PR, right?

**Pull request merged**
