### PR TITLE
Fix hint for "Diff with HEAD" feature

### PR DESCRIPTION
**Pull request by fo2rist**
It doesn't exit by [Spacebar], but it does by [Esc]

### CODE REVIEW

**Comment by lucasderraugh** [comment]
Hmm, I wonder if it ultimately should go away with Spacebar like other diff views (when you press Spacebar on a commit) but I agree this change at least reflects reality. Thanks.

**Review by lucasderraugh — APPROVED** [review]

**Comment by lucasderraugh** [comment]
@fo2rist Where does this text actually show up in the app. I can't seem to find where this is actually displayed 😅

**Comment by fo2rist** [comment]
@lucasderraugh I think I saw it in the pop-up hint (near the top of the window), that appears the first time you use the feature. Can't reproduce b/c I closed that hint once and it doesn't pop up anymore (as expected).

**Comment by fo2rist** [comment]
> Hmm, I wonder if it ultimately should go away with Spacebar like other diff views (when you press Spacebar on a commit) but I agree this change at least reflects reality. Thanks.

Good point, maybe it's better to fix the navigation instead, the commit view does exit by both Spacebar and Esc. The latter IMO is the must b/c that's what people click when they don't know what to click. So it looks to me like the Esc is the default key and Space is the shortcut for the most common action ("stage" in Working Directory, "exit" in Diff View).

If you can point me to the place where the hotkeys are registered I may be able to fix that once I have time (likely in 2021)

**Comment by lucasderraugh** [comment]
It's okay. For now I'll merge this in. I'm not sure that spacebar makes much sense to leave views you don't enter with space bar anyways. Thanks for this!

**Pull request merged**
