### PR TITLE
Toggle between Discard Selected and All depending on selection

### PR DESCRIPTION
**Pull request by lucasderraugh**
I realize there is the option to discard changes on the small gear button, but I find this to be someone inconvenient. Hopefully this is a desired change.
screen shot 2015-12-14 at 3 38 13 am
screen shot 2015-12-14 at 3 38 04 am

### CODE REVIEW

**Comment by swisspol** [comment]
To discard a single file from the index, just use the [Return] key :smile: http://forums.gitup.co/t/using-gitup-advanced-commit-view/33.

**Comment by alleus** [comment]
A note to future visitors searching for a solution, I'm using [Delete] in the Working Directory list to discard selected ([Return] stages the changes in the current version)

**Comment by brodock** [comment]
Can you reconsider this? While [delete] works, it doesn't add complexity to the interface changing button behavior. UX is important.

**Comment by mattdeluco** [comment]
How is this closed as "invalid"???

I just lost my whole morning of work because of this terrible UX!

**Comment by lucasderraugh** [comment]
I can look into adding the functionality back in a different PR.

**Pull request closed without merging**
